# Generated by Django 3.0.3 on 2020-07-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('student_id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
