# Generated by Django 3.0.3 on 2020-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200711_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gengo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='jinbun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kenkou',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kougaku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='senmon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='suuri',
            field=models.IntegerField(default=0),
        ),
    ]
