# Generated by Django 3.0.3 on 2020-06-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShibauraRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64, verbose_name='学科')),
                ('year', models.IntegerField(verbose_name='入学年度')),
                ('credit_for_graduation', models.IntegerField(verbose_name='卒業必須単位')),
                ('credit_for_research', models.IntegerField(verbose_name='卒検着手必須単位')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='科目名')),
                ('group', models.CharField(max_length=64, verbose_name='分類')),
                ('credit', models.IntegerField(verbose_name='単位数')),
                ('required', models.CharField(max_length=64, verbose_name='必修')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('term', models.IntegerField(verbose_name='期')),
                ('week', models.IntegerField(verbose_name='曜日')),
                ('period', models.IntegerField(verbose_name='時限')),
                ('place', models.CharField(max_length=64, verbose_name='開講場所')),
                ('teacher', models.CharField(max_length=64, verbose_name='教員氏名')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanni.Subject', verbose_name='科目id')),
            ],
        ),
    ]
