# Generated by Django 3.0.3 on 2020-06-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tanni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64, verbose_name='履修状況')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanni.Course', verbose_name='開講科目id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザid')),
            ],
        ),
    ]
