# Generated by Django 3.0.3 on 2020-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanni', '0002_usertimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='unit',
            field=models.IntegerField(default=1, verbose_name='コマ数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='required',
            field=models.CharField(default=1, max_length=64, verbose_name='必修'),
        ),
    ]
